-- Hydra initial schema (design.md §4.1, transcribed verbatim).
--
-- All tables use TEXT primary keys (UUID/ULID generated by the application).
-- `sqlx::migrate!` embeds this at compile time and manages the internal
-- `_sqlx_migrations` schema-version table automatically.

-- 供应商
CREATE TABLE provider (
    id        TEXT PRIMARY KEY,
    key       TEXT NOT NULL UNIQUE,        -- 供应商关键字
    name      TEXT NOT NULL,
    endpoint  TEXT NOT NULL,               -- 后端基地址，如 https://api.openai.com
    weight    INTEGER NOT NULL DEFAULT 1 CHECK (weight >= 0),  -- 0=软禁用（不参与 RR，详见 §7.2）
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 供应商提供的模型
CREATE TABLE provider_model (
    id          TEXT PRIMARY KEY,
    key         TEXT NOT NULL,             -- 模型英文关键字（路由依据）
    name        TEXT NOT NULL,             -- 模型名称
    provider_id TEXT NOT NULL REFERENCES provider(id) ON DELETE CASCADE,
    status      INTEGER NOT NULL DEFAULT 1 -- 1 在线 / 0 手动离线 / -1 探活离线（由后台健康任务写）
                  CHECK (status IN (1, 0, -1)),
    UNIQUE (key, provider_id)
);
CREATE INDEX idx_provider_model_key ON provider_model(key);
CREATE INDEX idx_provider_model_provider ON provider_model(provider_id);

-- 供应商 api-key
CREATE TABLE provider_key (
    id          TEXT PRIMARY KEY,
    provider_id TEXT NOT NULL REFERENCES provider(id) ON DELETE CASCADE,
    api_key     TEXT NOT NULL,             -- 明文存储（见 §16.2）
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_provider_key_provider ON provider_key(provider_id);

-- 租户
CREATE TABLE tenant (
    id        TEXT PRIMARY KEY,
    name      TEXT NOT NULL,
    domain    TEXT NOT NULL UNIQUE,        -- 关联域名（localhost 亦可）
    auth_url  TEXT NOT NULL,               -- 外部认证地址，必填（缺失则该租户请求一律拒绝）
    cert_key  TEXT,                        -- 证书密钥路径
    cert_file TEXT,                        -- 证书文件路径
    enabled   INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 租户可访问的供应商
CREATE TABLE tenant_provider (
    id          TEXT PRIMARY KEY,
    tenant_id   TEXT NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    provider_id TEXT NOT NULL REFERENCES provider(id) ON DELETE CASCADE,
    UNIQUE (tenant_id, provider_id)
);

-- 租户可访问的模型（model_key 引用 provider_model.key；作为访问闸门，详见 §7.1）
CREATE TABLE tenant_model (
    id        TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenant(id) ON DELETE CASCADE,
    model_key TEXT NOT NULL,
    UNIQUE (tenant_id, model_key)
);

-- 访问限制角色（任一 matching_* 为 NULL 表示匹配全部）
CREATE TABLE limit_role (
    id               TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    matching_key     TEXT,                 -- 匹配客户端 api-key（NULL=全部）
    matching_model   TEXT,                 -- 匹配 model（NULL=全部）
    matching_tenant  TEXT,                 -- 匹配租户 id（NULL=全部）
    matching_provider TEXT,                -- 匹配供应商 id（NULL=全部）
    limit_count      INTEGER,              -- 限额请求数（NULL=不限）
    limit_token      INTEGER,              -- 限额 token（NULL=不限）
    window           TEXT NOT NULL CHECK (window IN ('m', 'h', 'd')),
    enabled          INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 用量记录（默认 SQLite Sink）
CREATE TABLE usage_record (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    tenant_id         TEXT NOT NULL,
    provider_id       TEXT NOT NULL,
    model_key         TEXT NOT NULL,
    client_api_key    TEXT,                 -- 脱敏后的客户端 key（见 §9.5）
    status_code       INTEGER NOT NULL,
    prompt_tokens     INTEGER,
    completion_tokens INTEGER,
    total_tokens      INTEGER,
    latency_ms        INTEGER NOT NULL,
    upstream_host     TEXT,
    error             TEXT,
    created_at        TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_usage_record_created ON usage_record(created_at);
CREATE INDEX idx_usage_record_tenant ON usage_record(tenant_id, created_at);
